export type EventCategory = 'workshop' | 'cultural' | 'tech' | 'sports' | 'seminar' | 'hackathon';
export type EventMode = 'online' | 'offline' | 'hybrid';
export type AvailabilityStatus = 'Available' | 'Filling Fast' | 'Full';

export interface CollegeEvent {
  id: string;
  title: string;
  description: string;
  date: string;
  time: string;
  venue: string;
  category: EventCategory;
  mode: EventMode;
  organizer: string;
  department: string;
  googleFormLink: string;
  registrationLink?: string;
  posterUrl?: string;
  attendees: number;
  maxCapacity?: number;
  isFeatured?: boolean;
  eligibleDepartments: string[];
  availabilityStatus: AvailabilityStatus;
  createdBy: string;
  lastUpdatedBy: string;
  lastUpdatedAt: string;
}

// Generate future dates relative to today
const getFutureDate = (daysFromNow: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date.toISOString().split('T')[0];
};

// Sample Google Form links (placeholder URLs for demo)
const sampleGoogleFormLinks = [
  'https://forms.google.com/event-registration-1',
  'https://forms.google.com/event-registration-2',
  'https://forms.google.com/event-registration-3',
];

const getFormLink = (index: number) => sampleGoogleFormLinks[index % sampleGoogleFormLinks.length];

const now = new Date().toISOString();
const adminEmail = 'admin@college.edu';
const organizerEmail = 'organizer@college.edu';

const getAvailability = (attendees: number, maxCapacity?: number): AvailabilityStatus => {
  if (!maxCapacity) return 'Available';
  const pct = (attendees / maxCapacity) * 100;
  if (pct >= 100) return 'Full';
  if (pct >= 80) return 'Filling Fast';
  return 'Available';
};

export const sampleEvents: CollegeEvent[] = [
  // ==================== UPCOMING EVENTS (Future dates) ====================
  {
    id: '1',
    title: 'AI & Machine Learning Workshop',
    description: 'Hands-on workshop covering neural networks, deep learning fundamentals, and practical applications using Python and TensorFlow.',
    date: getFutureDate(5),
    time: '10:00 AM',
    venue: 'Computer Science Lab 301',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Tech Club',
    department: 'Department of Computer Science (UG)',
    googleFormLink: getFormLink(0),
    attendees: 45,
    maxCapacity: 60,
    isFeatured: true,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '2',
    title: 'Annual Cultural Fest - Rhythm 2025',
    description: 'Three-day extravaganza featuring music, dance, drama, and art competitions from colleges across the state.',
    date: getFutureDate(12),
    time: '5:00 PM',
    venue: 'Main Auditorium',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Cultural Committee',
    department: 'Department of Media Studies',
    googleFormLink: getFormLink(1),
    attendees: 500,
    maxCapacity: 800,
    isFeatured: true,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '3',
    title: 'Hackathon: Code for Change',
    description: '24-hour coding marathon to build innovative solutions for social impact. Great prizes and networking opportunities!',
    date: getFutureDate(18),
    time: '9:00 AM',
    venue: 'Innovation Hub',
    category: 'hackathon',
    mode: 'hybrid',
    organizer: 'Developer Community',
    department: 'Department of Computer Science (UG)',
    googleFormLink: getFormLink(2),
    attendees: 120,
    maxCapacity: 150,
    isFeatured: true,
    eligibleDepartments: ['Department of Computer Science (UG)', 'Department of Computer Science (PG)'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '4',
    title: 'Inter-College Basketball Championship',
    description: 'Annual basketball tournament featuring teams from 12 colleges. Come support your team!',
    date: getFutureDate(8),
    time: '2:00 PM',
    venue: 'Sports Complex',
    category: 'sports',
    mode: 'offline',
    organizer: 'Sports Council',
    department: 'Department of Physical Sciences',
    googleFormLink: getFormLink(0),
    attendees: 180,
    maxCapacity: 250,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '5',
    title: 'Guest Lecture: Future of Renewable Energy',
    description: 'Dr. Sarah Mitchell from MIT discusses the latest advancements in solar and wind energy technology.',
    date: getFutureDate(3),
    time: '3:00 PM',
    venue: 'Seminar Hall A',
    category: 'seminar',
    mode: 'hybrid',
    organizer: 'Energy Club',
    department: 'Department of Physical Sciences',
    googleFormLink: getFormLink(1),
    attendees: 80,
    maxCapacity: 100,
    eligibleDepartments: ['Department of Physical Sciences', 'Department of Life Sciences'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '6',
    title: 'Photography Workshop: Capture the Moment',
    description: 'Learn professional photography techniques including composition, lighting, and post-processing.',
    date: getFutureDate(20),
    time: '11:00 AM',
    venue: 'Art Studio',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Photography Club',
    department: 'Department of Media Studies',
    googleFormLink: getFormLink(2),
    attendees: 25,
    maxCapacity: 30,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '7',
    title: 'Startup Pitch Competition',
    description: 'Present your startup idea to a panel of investors and industry experts. Win funding and mentorship!',
    date: getFutureDate(25),
    time: '10:00 AM',
    venue: 'Business School Auditorium',
    category: 'tech',
    mode: 'offline',
    organizer: 'Entrepreneurship Cell',
    department: 'Department of Management',
    googleFormLink: getFormLink(0),
    attendees: 60,
    maxCapacity: 80,
    eligibleDepartments: ['Department of Management', 'Department of Computer Science (UG)', 'Department of Commerce'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '8',
    title: 'Classical Music Night',
    description: 'An evening of Indian classical music featuring renowned artists and student performers.',
    date: getFutureDate(15),
    time: '6:30 PM',
    venue: 'Open Air Theatre',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Music Society',
    department: 'Department of Media Studies',
    googleFormLink: getFormLink(1),
    attendees: 120,
    maxCapacity: 200,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '9',
    title: 'Web Development Bootcamp',
    description: 'Intensive 2-day bootcamp covering React, Node.js, and modern web development practices.',
    date: getFutureDate(0),
    time: '9:00 AM',
    venue: 'Tech Lab 201',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Web Dev Club',
    department: 'Department of Computer Science (UG)',
    googleFormLink: getFormLink(2),
    attendees: 35,
    maxCapacity: 40,
    eligibleDepartments: ['Department of Computer Science (UG)', 'Department of Computer Science (PG)'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '10',
    title: 'Career Fair 2025',
    description: 'Connect with top employers, explore internship opportunities, and get your resume reviewed.',
    date: getFutureDate(30),
    time: '10:00 AM',
    venue: 'Main Hall',
    category: 'seminar',
    mode: 'offline',
    organizer: 'Placement Cell',
    department: 'Department of Management',
    googleFormLink: getFormLink(0),
    attendees: 250,
    maxCapacity: 500,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '11',
    title: 'Yoga & Wellness Session',
    description: 'Start your morning with guided yoga and meditation for stress relief and mental clarity.',
    date: getFutureDate(2),
    time: '6:00 AM',
    venue: 'Sports Ground',
    category: 'sports',
    mode: 'offline',
    organizer: 'Wellness Club',
    department: 'Department of Psychology',
    googleFormLink: getFormLink(1),
    attendees: 40,
    maxCapacity: 50,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Filling Fast',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '12',
    title: 'Data Science Symposium',
    description: 'Industry experts discuss the latest trends in data analytics, visualization, and business intelligence.',
    date: getFutureDate(22),
    time: '2:00 PM',
    venue: 'Conference Hall B',
    category: 'seminar',
    mode: 'hybrid',
    organizer: 'Data Science Club',
    department: 'Department of Computer Science (PG)',
    googleFormLink: getFormLink(2),
    attendees: 90,
    maxCapacity: 120,
    eligibleDepartments: ['Department of Computer Science (UG)', 'Department of Computer Science (PG)', 'Department of Physical Sciences'],
    availabilityStatus: 'Available',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '16',
    title: 'Cybersecurity Essentials Workshop',
    description: 'Learn about network security, ethical hacking basics, and protecting digital assets in this hands-on session.',
    date: getFutureDate(4),
    time: '2:00 PM',
    venue: 'IT Lab 102',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Cyber Club',
    department: 'Department of Computer Science (UG)',
    googleFormLink: getFormLink(0),
    attendees: 28,
    maxCapacity: 40,
    eligibleDepartments: ['Department of Computer Science (UG)', 'Department of Computer Science (PG)'],
    availabilityStatus: 'Available',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '17',
    title: 'Annual Sports Day',
    description: 'A full day of athletic competitions including track events, field sports, and team games for all departments.',
    date: getFutureDate(10),
    time: '8:00 AM',
    venue: 'University Stadium',
    category: 'sports',
    mode: 'offline',
    organizer: 'Sports Council',
    department: 'Department of Physical Sciences',
    googleFormLink: getFormLink(1),
    attendees: 350,
    maxCapacity: 500,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '18',
    title: 'Blockchain Technology Seminar',
    description: 'Understanding decentralized systems, smart contracts, and the future of Web3 technologies.',
    date: getFutureDate(7),
    time: '11:00 AM',
    venue: 'Seminar Hall B',
    category: 'seminar',
    mode: 'hybrid',
    organizer: 'Tech Club',
    department: 'Department of Computer Science (UG)',
    googleFormLink: getFormLink(2),
    attendees: 55,
    maxCapacity: 80,
    eligibleDepartments: ['Department of Computer Science (UG)', 'Department of Management'],
    availabilityStatus: 'Available',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '19',
    title: 'Dance Workshop: Contemporary Fusion',
    description: 'Master contemporary dance techniques blending classical and modern styles with professional choreographers.',
    date: getFutureDate(6),
    time: '4:00 PM',
    venue: 'Dance Studio',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Dance Club',
    department: 'Department of Media Studies',
    googleFormLink: getFormLink(0),
    attendees: 18,
    maxCapacity: 25,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '20',
    title: 'IoT Innovation Challenge',
    description: 'Build smart devices and IoT solutions using Arduino and Raspberry Pi. Best projects win exciting prizes!',
    date: getFutureDate(14),
    time: '9:00 AM',
    venue: 'Electronics Lab',
    category: 'hackathon',
    mode: 'offline',
    organizer: 'Electronics Club',
    department: 'Department of Physical Sciences',
    googleFormLink: getFormLink(1),
    attendees: 42,
    maxCapacity: 50,
    eligibleDepartments: ['Department of Physical Sciences', 'Department of Computer Science (UG)', 'Department of Computer Science (PG)'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '21',
    title: 'Public Speaking Masterclass',
    description: 'Develop confidence, learn persuasion techniques, and master the art of impactful presentations.',
    date: getFutureDate(9),
    time: '3:00 PM',
    venue: 'Conference Room A',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Toastmasters Club',
    department: 'Department of Social Sciences and Languages',
    googleFormLink: getFormLink(2),
    attendees: 30,
    maxCapacity: 35,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Filling Fast',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '22',
    title: 'Inter-Department Cricket Tournament',
    description: 'Annual cricket championship between departments. Register your team and compete for the trophy!',
    date: getFutureDate(16),
    time: '7:00 AM',
    venue: 'Cricket Ground',
    category: 'sports',
    mode: 'offline',
    organizer: 'Sports Council',
    department: 'Department of Physical Sciences',
    googleFormLink: getFormLink(0),
    attendees: 160,
    maxCapacity: 200,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Filling Fast',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '23',
    title: 'Film Making & Editing Workshop',
    description: 'Learn cinematography, video editing, and storytelling techniques from industry professionals.',
    date: getFutureDate(11),
    time: '10:00 AM',
    venue: 'Media Lab',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Film Club',
    department: 'Department of Media Studies',
    googleFormLink: getFormLink(1),
    attendees: 22,
    maxCapacity: 30,
    eligibleDepartments: ['Department of Media Studies', 'Department of Social Sciences and Languages'],
    availabilityStatus: 'Available',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '24',
    title: 'Mental Health Awareness Talk',
    description: 'Expert psychologists discuss stress management, work-life balance, and maintaining mental wellness.',
    date: getFutureDate(1),
    time: '2:30 PM',
    venue: 'Main Auditorium',
    category: 'seminar',
    mode: 'hybrid',
    organizer: 'Counseling Center',
    department: 'Department of Psychology',
    googleFormLink: getFormLink(2),
    attendees: 180,
    maxCapacity: 300,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '25',
    title: 'Robotics Competition 2025',
    description: 'Design, build, and program robots to complete challenging tasks. Open to all engineering students.',
    date: getFutureDate(21),
    time: '9:00 AM',
    venue: 'Robotics Lab',
    category: 'hackathon',
    mode: 'offline',
    organizer: 'Robotics Club',
    department: 'Department of Physical Sciences',
    googleFormLink: getFormLink(0),
    attendees: 65,
    maxCapacity: 80,
    eligibleDepartments: ['Department of Physical Sciences', 'Department of Computer Science (UG)', 'Department of Computer Science (PG)'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '26',
    title: 'Poetry Slam & Open Mic Night',
    description: 'Express yourself through poetry, spoken word, and creative performances in a supportive atmosphere.',
    date: getFutureDate(13),
    time: '6:00 PM',
    venue: 'Literary Cafe',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Literary Society',
    department: 'Department of English',
    googleFormLink: getFormLink(1),
    attendees: 45,
    maxCapacity: 60,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '27',
    title: 'Mobile App Development Sprint',
    description: 'Build a complete mobile app in 48 hours using Flutter or React Native with expert mentorship.',
    date: getFutureDate(19),
    time: '10:00 AM',
    venue: 'Innovation Hub',
    category: 'hackathon',
    mode: 'hybrid',
    organizer: 'App Dev Club',
    department: 'Department of Computer Science (UG)',
    googleFormLink: getFormLink(2),
    attendees: 38,
    maxCapacity: 45,
    eligibleDepartments: ['Department of Computer Science (UG)'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '28',
    title: 'Cloud Computing Fundamentals',
    description: 'Introduction to AWS, Azure, and Google Cloud. Learn to deploy scalable applications in the cloud.',
    date: getFutureDate(4),
    time: '10:00 AM',
    venue: 'IT Lab 201',
    category: 'workshop',
    mode: 'hybrid',
    organizer: 'Cloud Computing Club',
    department: 'Department of Computer Science (PG)',
    googleFormLink: getFormLink(0),
    attendees: 32,
    maxCapacity: 50,
    eligibleDepartments: ['Department of Computer Science (UG)', 'Department of Computer Science (PG)'],
    availabilityStatus: 'Available',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '29',
    title: 'Annual Theatre Festival',
    description: 'A week-long celebration of drama featuring student productions, workshops, and guest performances.',
    date: getFutureDate(23),
    time: '4:00 PM',
    venue: 'Drama Theatre',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Theatre Society',
    department: 'Department of Media Studies',
    googleFormLink: getFormLink(1),
    attendees: 180,
    maxCapacity: 250,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '30',
    title: 'Swimming Championship 2025',
    description: 'Inter-college swimming competition with events in freestyle, backstroke, butterfly, and relay.',
    date: getFutureDate(17),
    time: '8:00 AM',
    venue: 'Olympic Pool',
    category: 'sports',
    mode: 'offline',
    organizer: 'Aquatics Club',
    department: 'Department of Physical Sciences',
    googleFormLink: getFormLink(2),
    attendees: 85,
    maxCapacity: 120,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '31',
    title: 'Digital Marketing Bootcamp',
    description: 'Master SEO, social media marketing, content strategy, and analytics in this intensive workshop.',
    date: getFutureDate(6),
    time: '9:30 AM',
    venue: 'Business Lab',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Marketing Club',
    department: 'Department of Management',
    googleFormLink: getFormLink(0),
    attendees: 40,
    maxCapacity: 45,
    eligibleDepartments: ['Department of Management', 'Department of Commerce', 'Department of Media Studies'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '32',
    title: 'Quantum Computing Symposium',
    description: 'Leading researchers discuss quantum algorithms, hardware developments, and industry applications.',
    date: getFutureDate(28),
    time: '10:00 AM',
    venue: 'Conference Hall A',
    category: 'seminar',
    mode: 'hybrid',
    organizer: 'Physics Society',
    department: 'Department of Physical Sciences',
    googleFormLink: getFormLink(1),
    attendees: 75,
    maxCapacity: 100,
    eligibleDepartments: ['Department of Physical Sciences', 'Department of Computer Science (UG)', 'Department of Computer Science (PG)'],
    availabilityStatus: 'Available',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '33',
    title: 'International Food Festival',
    description: 'Experience cuisines from around the world prepared by student clubs. Cultural performances included.',
    date: getFutureDate(15),
    time: '12:00 PM',
    venue: 'Central Lawn',
    category: 'cultural',
    mode: 'offline',
    organizer: 'International Students Association',
    department: 'Department of Social Sciences and Languages',
    googleFormLink: getFormLink(2),
    attendees: 400,
    maxCapacity: 600,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '34',
    title: 'Game Development Workshop',
    description: 'Create your first video game using Unity. Learn game design principles and C# programming basics.',
    date: getFutureDate(8),
    time: '2:00 PM',
    venue: 'Gaming Lab',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Game Dev Society',
    department: 'Department of Computer Science (UG)',
    googleFormLink: getFormLink(0),
    attendees: 28,
    maxCapacity: 35,
    eligibleDepartments: ['Department of Computer Science (UG)', 'Department of Media Studies'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '35',
    title: 'Badminton Tournament',
    description: 'Singles and doubles categories open to all students. Registration includes practice sessions.',
    date: getFutureDate(12),
    time: '3:00 PM',
    venue: 'Indoor Sports Hall',
    category: 'sports',
    mode: 'offline',
    organizer: 'Badminton Club',
    department: 'Department of Physical Sciences',
    googleFormLink: getFormLink(1),
    attendees: 64,
    maxCapacity: 80,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Filling Fast',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '36',
    title: 'UI/UX Design Masterclass',
    description: 'Learn user research, wireframing, prototyping, and design systems using Figma and Adobe XD.',
    date: getFutureDate(5),
    time: '11:00 AM',
    venue: 'Design Studio',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Design Club',
    department: 'Department of Media Studies',
    googleFormLink: getFormLink(2),
    attendees: 25,
    maxCapacity: 30,
    eligibleDepartments: ['Department of Media Studies', 'Department of Computer Science (UG)', 'Department of Social Sciences and Languages'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '37',
    title: 'Astronomy Night: Stargazing Session',
    description: 'Observe planets, constellations, and deep-sky objects through powerful telescopes on campus.',
    date: getFutureDate(10),
    time: '8:00 PM',
    venue: 'Observatory Terrace',
    category: 'seminar',
    mode: 'offline',
    organizer: 'Astronomy Club',
    department: 'Department of Physical Sciences',
    googleFormLink: getFormLink(0),
    attendees: 50,
    maxCapacity: 60,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '38',
    title: 'Debate Championship 2025',
    description: 'Annual inter-college debate competition on current affairs and policy topics. Cash prizes await!',
    date: getFutureDate(20),
    time: '10:00 AM',
    venue: 'Seminar Hall C',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Debate Society',
    department: 'Department of English',
    googleFormLink: getFormLink(1),
    attendees: 60,
    maxCapacity: 80,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '39',
    title: 'Python for Data Analysis',
    description: 'Hands-on workshop covering pandas, numpy, matplotlib for data manipulation and visualization.',
    date: getFutureDate(3),
    time: '10:00 AM',
    venue: 'Computer Lab 102',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Data Science Club',
    department: 'Department of Computer Science (UG)',
    googleFormLink: getFormLink(2),
    attendees: 42,
    maxCapacity: 50,
    eligibleDepartments: ['Department of Computer Science (UG)', 'Department of Computer Science (PG)', 'Department of Physical Sciences'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '40',
    title: 'Chess Championship',
    description: 'Open chess tournament with classical and rapid formats. All skill levels welcome.',
    date: getFutureDate(14),
    time: '9:00 AM',
    venue: 'Recreation Room',
    category: 'sports',
    mode: 'offline',
    organizer: 'Chess Club',
    department: 'Department of Social Sciences and Languages',
    googleFormLink: getFormLink(0),
    attendees: 48,
    maxCapacity: 64,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '41',
    title: 'Entrepreneurship Summit 2025',
    description: 'Successful founders share their journeys. Includes networking sessions and startup showcases.',
    date: getFutureDate(26),
    time: '9:00 AM',
    venue: 'Business Auditorium',
    category: 'seminar',
    mode: 'hybrid',
    organizer: 'E-Cell',
    department: 'Department of Management',
    googleFormLink: getFormLink(1),
    attendees: 200,
    maxCapacity: 300,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '42',
    title: 'Electronic Music Production',
    description: 'Learn beat making, mixing, and mastering using Ableton Live and FL Studio.',
    date: getFutureDate(9),
    time: '3:00 PM',
    venue: 'Music Studio',
    category: 'workshop',
    mode: 'offline',
    organizer: 'EDM Club',
    department: 'Department of Media Studies',
    googleFormLink: getFormLink(2),
    attendees: 15,
    maxCapacity: 20,
    eligibleDepartments: ['Department of Media Studies', 'Department of Social Sciences and Languages'],
    availabilityStatus: 'Available',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '43',
    title: 'Hackathon: HealthTech Innovation',
    description: 'Build healthcare solutions using AI, IoT, and mobile tech. Mentorship from medical professionals.',
    date: getFutureDate(24),
    time: '8:00 AM',
    venue: 'Innovation Center',
    category: 'hackathon',
    mode: 'hybrid',
    organizer: 'Health Tech Club',
    department: 'Department of Life Sciences',
    googleFormLink: getFormLink(0),
    attendees: 80,
    maxCapacity: 100,
    eligibleDepartments: ['Department of Life Sciences', 'Department of Computer Science (UG)', 'Department of Computer Science (PG)'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '44',
    title: 'Table Tennis League',
    description: 'Weekly league format with playoffs. Individual and doubles categories available.',
    date: getFutureDate(7),
    time: '5:00 PM',
    venue: 'TT Room',
    category: 'sports',
    mode: 'offline',
    organizer: 'TT Club',
    department: 'Department of Physical Sciences',
    googleFormLink: getFormLink(1),
    attendees: 32,
    maxCapacity: 40,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Filling Fast',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '45',
    title: 'Fashion Show: Threads 2025',
    description: 'Annual fashion showcase featuring student designers. Themes: sustainable fashion and cultural fusion.',
    date: getFutureDate(27),
    time: '7:00 PM',
    venue: 'Grand Ballroom',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Fashion Club',
    department: 'Department of Media Studies',
    googleFormLink: getFormLink(2),
    attendees: 350,
    maxCapacity: 500,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '46',
    title: 'Linux System Administration',
    description: 'Master command line, shell scripting, and server management for enterprise environments.',
    date: getFutureDate(11),
    time: '10:00 AM',
    venue: 'Server Room Lab',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Open Source Club',
    department: 'Department of Computer Science (PG)',
    googleFormLink: getFormLink(0),
    attendees: 22,
    maxCapacity: 25,
    eligibleDepartments: ['Department of Computer Science (UG)', 'Department of Computer Science (PG)'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '47',
    title: 'Marathon: Run for Health',
    description: '5K, 10K, and half-marathon categories. All participants receive medals and refreshments.',
    date: getFutureDate(29),
    time: '6:00 AM',
    venue: 'Campus Circuit',
    category: 'sports',
    mode: 'offline',
    organizer: 'Athletics Club',
    department: 'Department of Physical Sciences',
    googleFormLink: getFormLink(1),
    attendees: 280,
    maxCapacity: 400,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '48',
    title: 'DevOps & CI/CD Pipeline Workshop',
    description: 'Learn Docker, Kubernetes, Jenkins, and GitHub Actions for modern software deployment workflows.',
    date: getFutureDate(4),
    time: '9:00 AM',
    venue: 'Cloud Lab 101',
    category: 'workshop',
    mode: 'hybrid',
    organizer: 'DevOps Club',
    department: 'Department of Computer Science (PG)',
    googleFormLink: getFormLink(0),
    attendees: 35,
    maxCapacity: 45,
    eligibleDepartments: ['Department of Computer Science (UG)', 'Department of Computer Science (PG)'],
    availabilityStatus: 'Available',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '49',
    title: 'Stand-Up Comedy Night',
    description: 'Laugh out loud with performances from campus comedians and special guest artists.',
    date: getFutureDate(8),
    time: '7:30 PM',
    venue: 'Open Air Theatre',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Comedy Club',
    department: 'Department of Social Sciences and Languages',
    googleFormLink: getFormLink(1),
    attendees: 180,
    maxCapacity: 250,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '50',
    title: 'Volleyball Championship 2025',
    description: 'Inter-department volleyball tournament with mens and womens categories. Register your team now!',
    date: getFutureDate(13),
    time: '3:00 PM',
    venue: 'Volleyball Court',
    category: 'sports',
    mode: 'offline',
    organizer: 'Sports Council',
    department: 'Department of Physical Sciences',
    googleFormLink: getFormLink(2),
    attendees: 120,
    maxCapacity: 160,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '51',
    title: 'Machine Learning with TensorFlow',
    description: 'Build and deploy ML models using TensorFlow 2.0. Includes hands-on projects and model optimization.',
    date: getFutureDate(6),
    time: '10:00 AM',
    venue: 'AI Research Lab',
    category: 'workshop',
    mode: 'offline',
    organizer: 'AI Club',
    department: 'Department of Computer Science (PG)',
    googleFormLink: getFormLink(0),
    attendees: 38,
    maxCapacity: 40,
    eligibleDepartments: ['Department of Computer Science (UG)', 'Department of Computer Science (PG)'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '52',
    title: 'Environmental Sustainability Summit',
    description: 'Experts discuss climate change, green technologies, and sustainable campus initiatives.',
    date: getFutureDate(18),
    time: '10:00 AM',
    venue: 'Conference Hall A',
    category: 'seminar',
    mode: 'hybrid',
    organizer: 'Green Campus Initiative',
    department: 'Department of Life Sciences',
    googleFormLink: getFormLink(1),
    attendees: 150,
    maxCapacity: 200,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '53',
    title: 'K-Pop Dance Cover Competition',
    description: 'Show off your best K-Pop dance moves! Solo and group categories with exciting prizes.',
    date: getFutureDate(16),
    time: '5:00 PM',
    venue: 'Main Auditorium',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Korean Culture Club',
    department: 'Department of Media Studies',
    googleFormLink: getFormLink(2),
    attendees: 200,
    maxCapacity: 300,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '54',
    title: 'Ethical Hacking Bootcamp',
    description: 'Learn penetration testing, vulnerability assessment, and security auditing techniques.',
    date: getFutureDate(9),
    time: '9:00 AM',
    venue: 'Security Lab',
    category: 'hackathon',
    mode: 'offline',
    organizer: 'Cyber Security Club',
    department: 'Department of Computer Science (UG)',
    googleFormLink: getFormLink(0),
    attendees: 28,
    maxCapacity: 35,
    eligibleDepartments: ['Department of Computer Science (UG)', 'Department of Computer Science (PG)'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '55',
    title: 'Football League Finals',
    description: 'Watch the top two teams battle for the championship trophy. Food stalls and live commentary!',
    date: getFutureDate(22),
    time: '4:00 PM',
    venue: 'Football Stadium',
    category: 'sports',
    mode: 'offline',
    organizer: 'Football Club',
    department: 'Department of Physical Sciences',
    googleFormLink: getFormLink(1),
    attendees: 450,
    maxCapacity: 600,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '56',
    title: 'Creative Writing Workshop',
    description: 'Develop your storytelling skills with fiction writing techniques and character development.',
    date: getFutureDate(5),
    time: '2:00 PM',
    venue: 'Library Hall',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Writers Guild',
    department: 'Department of English',
    googleFormLink: getFormLink(2),
    attendees: 20,
    maxCapacity: 25,
    eligibleDepartments: ['Department of English', 'Department of Social Sciences and Languages', 'Department of Media Studies'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '57',
    title: 'FinTech Innovation Conference',
    description: 'Explore blockchain in finance, digital payments, and the future of banking with industry leaders.',
    date: getFutureDate(25),
    time: '9:30 AM',
    venue: 'Business School Auditorium',
    category: 'seminar',
    mode: 'hybrid',
    organizer: 'Finance Club',
    department: 'Department of Professional Accounting & Finance',
    googleFormLink: getFormLink(0),
    attendees: 180,
    maxCapacity: 250,
    eligibleDepartments: ['Department of Professional Accounting & Finance', 'Department of Commerce', 'Department of Economics'],
    availabilityStatus: 'Available',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '58',
    title: 'Acoustic Music Jam Session',
    description: 'Unplugged performances featuring guitar, vocals, and percussion. Open mic slots available!',
    date: getFutureDate(7),
    time: '6:00 PM',
    venue: 'Campus Cafe',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Music Society',
    department: 'Department of Media Studies',
    googleFormLink: getFormLink(1),
    attendees: 60,
    maxCapacity: 80,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '59',
    title: 'AR/VR Development Workshop',
    description: 'Build immersive experiences using Unity and Oculus SDK. Headsets provided for practice.',
    date: getFutureDate(12),
    time: '10:00 AM',
    venue: 'VR Lab',
    category: 'workshop',
    mode: 'offline',
    organizer: 'XR Club',
    department: 'Department of Computer Science (UG)',
    googleFormLink: getFormLink(2),
    attendees: 18,
    maxCapacity: 20,
    eligibleDepartments: ['Department of Computer Science (UG)', 'Department of Media Studies'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '60',
    title: 'Archery Training Camp',
    description: 'Learn traditional and Olympic archery techniques. Equipment and safety gear provided.',
    date: getFutureDate(19),
    time: '7:00 AM',
    venue: 'Archery Range',
    category: 'sports',
    mode: 'offline',
    organizer: 'Archery Club',
    department: 'Department of Physical Sciences',
    googleFormLink: getFormLink(0),
    attendees: 24,
    maxCapacity: 30,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Filling Fast',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '61',
    title: 'AI Art Generation Workshop',
    description: 'Create stunning artwork using DALL-E, Midjourney, and Stable Diffusion. Explore prompt engineering.',
    date: getFutureDate(3),
    time: '3:00 PM',
    venue: 'Digital Arts Lab',
    category: 'workshop',
    mode: 'hybrid',
    organizer: 'AI Art Collective',
    department: 'Department of Media Studies',
    googleFormLink: getFormLink(1),
    attendees: 30,
    maxCapacity: 35,
    eligibleDepartments: ['Department of Media Studies', 'Department of Computer Science (UG)'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '62',
    title: 'TEDx Campus 2025',
    description: 'Ideas worth spreading! Student and guest speakers share inspiring talks on innovation and change.',
    date: getFutureDate(30),
    time: '10:00 AM',
    venue: 'Main Auditorium',
    category: 'seminar',
    mode: 'hybrid',
    organizer: 'TEDx Team',
    department: 'Department of Social Sciences and Languages',
    googleFormLink: getFormLink(2),
    attendees: 380,
    maxCapacity: 500,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '63',
    title: 'Bollywood Dance Workshop',
    description: 'Learn popular Bollywood choreography from professional dancers. All skill levels welcome!',
    date: getFutureDate(11),
    time: '4:30 PM',
    venue: 'Dance Studio',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Bollywood Club',
    department: 'Department of Media Studies',
    googleFormLink: getFormLink(0),
    attendees: 45,
    maxCapacity: 50,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Filling Fast',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '64',
    title: 'API Design & Development',
    description: 'Master RESTful APIs, GraphQL, and API security best practices with real-world projects.',
    date: getFutureDate(14),
    time: '10:00 AM',
    venue: 'Tech Lab 301',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Backend Dev Club',
    department: 'Department of Computer Science (PG)',
    googleFormLink: getFormLink(1),
    attendees: 32,
    maxCapacity: 40,
    eligibleDepartments: ['Department of Computer Science (UG)', 'Department of Computer Science (PG)'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '65',
    title: 'Kabaddi Tournament 2025',
    description: 'Traditional Indian sport competition between departments. Experience the thrill of contact sport!',
    date: getFutureDate(21),
    time: '2:00 PM',
    venue: 'Indoor Stadium',
    category: 'sports',
    mode: 'offline',
    organizer: 'Traditional Sports Club',
    department: 'Department of Physical Sciences',
    googleFormLink: getFormLink(2),
    attendees: 100,
    maxCapacity: 150,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '66',
    title: 'Anime & Manga Festival',
    description: 'Cosplay competition, anime screenings, manga swap meet, and Japanese culture activities.',
    date: getFutureDate(17),
    time: '11:00 AM',
    venue: 'Student Center',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Anime Club',
    department: 'Department of Social Sciences and Languages',
    googleFormLink: getFormLink(0),
    attendees: 250,
    maxCapacity: 350,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Available',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '67',
    title: 'Smart Contract Development',
    description: 'Build decentralized applications on Ethereum using Solidity. Deploy your first DApp!',
    date: getFutureDate(23),
    time: '9:00 AM',
    venue: 'Blockchain Lab',
    category: 'hackathon',
    mode: 'hybrid',
    organizer: 'Web3 Club',
    department: 'Department of Computer Science (UG)',
    googleFormLink: getFormLink(1),
    attendees: 40,
    maxCapacity: 50,
    eligibleDepartments: ['Department of Computer Science (UG)', 'Department of Computer Science (PG)'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '68',
    title: 'Forensic Science Workshop',
    description: 'Hands-on workshop on crime scene investigation, evidence collection, and forensic analysis techniques.',
    date: getFutureDate(10),
    time: '10:00 AM',
    venue: 'Forensic Lab',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Forensic Society',
    department: 'Department of Forensic Science',
    googleFormLink: getFormLink(0),
    attendees: 30,
    maxCapacity: 40,
    eligibleDepartments: ['Department of Forensic Science', 'Department of Law (School of Law)'],
    availabilityStatus: 'Available',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '69',
    title: 'Moot Court Competition',
    description: 'Annual moot court competition for law students. Present arguments before a panel of judges.',
    date: getFutureDate(15),
    time: '9:00 AM',
    venue: 'Moot Court Hall',
    category: 'seminar',
    mode: 'offline',
    organizer: 'Law Society',
    department: 'Department of Law (School of Law)',
    googleFormLink: getFormLink(1),
    attendees: 60,
    maxCapacity: 80,
    eligibleDepartments: ['Department of Law (School of Law)'],
    availabilityStatus: 'Available',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '70',
    title: 'Social Work Field Visit Orientation',
    description: 'Orientation session for upcoming community fieldwork. Learn about partner NGOs and project goals.',
    date: getFutureDate(4),
    time: '11:00 AM',
    venue: 'Social Work Block',
    category: 'seminar',
    mode: 'offline',
    organizer: 'Social Work Department',
    department: 'Department of Social Work',
    googleFormLink: getFormLink(2),
    attendees: 40,
    maxCapacity: 50,
    eligibleDepartments: ['Department of Social Work', 'Department of Psychology'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '71',
    title: 'Professional Management Case Study Competition',
    description: 'Analyze real-world business cases and present strategic solutions to industry judges.',
    date: getFutureDate(20),
    time: '10:00 AM',
    venue: 'MBA Block Auditorium',
    category: 'tech',
    mode: 'offline',
    organizer: 'PMS Association',
    department: 'Department of Professional Management Studies',
    googleFormLink: getFormLink(0),
    attendees: 80,
    maxCapacity: 100,
    eligibleDepartments: ['Department of Professional Management Studies', 'Department of Management', 'Department of Commerce'],
    availabilityStatus: 'Filling Fast',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  // ==================== COMPLETED EVENTS (Past dates) ====================
  {
    id: '13',
    title: 'Orientation Week 2024',
    description: 'Welcome session for new students with campus tours and introduction to university life.',
    date: getFutureDate(-30),
    time: '9:00 AM',
    venue: 'Main Auditorium',
    category: 'seminar',
    mode: 'offline',
    organizer: 'Student Council',
    department: 'Department of Social Sciences and Languages',
    googleFormLink: getFormLink(0),
    attendees: 600,
    maxCapacity: 600,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Full',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
  {
    id: '14',
    title: 'Coding Competition 2024',
    description: 'Annual competitive programming event with algorithmic challenges for all skill levels.',
    date: getFutureDate(-15),
    time: '10:00 AM',
    venue: 'Computer Lab 101',
    category: 'tech',
    mode: 'offline',
    organizer: 'Coding Club',
    department: 'Department of Computer Science (UG)',
    googleFormLink: getFormLink(1),
    attendees: 75,
    maxCapacity: 75,
    eligibleDepartments: ['Department of Computer Science (UG)', 'Department of Computer Science (PG)'],
    availabilityStatus: 'Full',
    createdBy: organizerEmail,
    lastUpdatedBy: organizerEmail,
    lastUpdatedAt: now,
  },
  {
    id: '15',
    title: 'Art Exhibition: Colors of Culture',
    description: 'Showcase of student artwork exploring themes of cultural diversity and heritage traditions.',
    date: getFutureDate(-7),
    time: '11:00 AM',
    venue: 'Art Gallery',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Art Society',
    department: 'Department of Media Studies',
    googleFormLink: getFormLink(2),
    attendees: 200,
    maxCapacity: 200,
    eligibleDepartments: ['All'],
    availabilityStatus: 'Full',
    createdBy: adminEmail,
    lastUpdatedBy: adminEmail,
    lastUpdatedAt: now,
  },
];

export const categories: { value: EventCategory; label: string; color: string }[] = [
  { value: 'workshop', label: 'Workshop', color: 'category-workshop' },
  { value: 'cultural', label: 'Cultural', color: 'category-cultural' },
  { value: 'tech', label: 'Tech', color: 'category-tech' },
  { value: 'sports', label: 'Sports', color: 'category-sports' },
  { value: 'seminar', label: 'Seminar', color: 'category-seminar' },
  { value: 'hackathon', label: 'Hackathon', color: 'category-tech' },
];

export const getCategoryColor = (category: EventCategory): string => {
  const cat = categories.find(c => c.value === category);
  return cat?.color || 'category-tech';
};
