export type EventCategory = 'workshop' | 'cultural' | 'tech' | 'sports' | 'seminar' | 'hackathon';
export type EventMode = 'online' | 'offline' | 'hybrid';

export interface CollegeEvent {
  id: string;
  title: string;
  description: string;
  date: string;
  time: string;
  venue: string;
  category: EventCategory;
  mode: EventMode;
  organizer: string;
  department: string;
  googleFormLink: string; // Required - all registrations via Google Form
  registrationLink?: string;
  posterUrl?: string;
  attendees: number;
  maxCapacity?: number;
  isFeatured?: boolean;
}

// Generate future dates relative to today
const getFutureDate = (daysFromNow: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date.toISOString().split('T')[0];
};

// Sample Google Form links (placeholder URLs for demo)
const sampleGoogleFormLinks = [
  'https://forms.google.com/event-registration-1',
  'https://forms.google.com/event-registration-2',
  'https://forms.google.com/event-registration-3',
];

const getFormLink = (index: number) => sampleGoogleFormLinks[index % sampleGoogleFormLinks.length];

export const sampleEvents: CollegeEvent[] = [
  // ==================== UPCOMING EVENTS (Future dates) ====================
  {
    id: '1',
    title: 'AI & Machine Learning Workshop',
    description: 'Hands-on workshop covering neural networks, deep learning fundamentals, and practical applications using Python and TensorFlow.',
    date: getFutureDate(5),
    time: '10:00 AM',
    venue: 'Computer Science Lab 301',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Tech Club',
    department: 'Computer Science',
    googleFormLink: getFormLink(0),
    attendees: 45,
    maxCapacity: 60,
    isFeatured: true,
  },
  {
    id: '2',
    title: 'Annual Cultural Fest - Rhythm 2025',
    description: 'Three-day extravaganza featuring music, dance, drama, and art competitions from colleges across the state.',
    date: getFutureDate(12),
    time: '5:00 PM',
    venue: 'Main Auditorium',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Cultural Committee',
    department: 'Student Affairs',
    googleFormLink: getFormLink(1),
    attendees: 500,
    maxCapacity: 800,
    isFeatured: true,
  },
  {
    id: '3',
    title: 'Hackathon: Code for Change',
    description: '24-hour coding marathon to build innovative solutions for social impact. Great prizes and networking opportunities!',
    date: getFutureDate(18),
    time: '9:00 AM',
    venue: 'Innovation Hub',
    category: 'hackathon',
    mode: 'hybrid',
    organizer: 'Developer Community',
    department: 'Computer Science',
    googleFormLink: getFormLink(2),
    attendees: 120,
    maxCapacity: 150,
    isFeatured: true,
  },
  {
    id: '4',
    title: 'Inter-College Basketball Championship',
    description: 'Annual basketball tournament featuring teams from 12 colleges. Come support your team!',
    date: getFutureDate(8),
    time: '2:00 PM',
    venue: 'Sports Complex',
    category: 'sports',
    mode: 'offline',
    organizer: 'Sports Council',
    department: 'Physical Education',
    googleFormLink: getFormLink(0),
    attendees: 180,
    maxCapacity: 250,
  },
  {
    id: '5',
    title: 'Guest Lecture: Future of Renewable Energy',
    description: 'Dr. Sarah Mitchell from MIT discusses the latest advancements in solar and wind energy technology.',
    date: getFutureDate(3),
    time: '3:00 PM',
    venue: 'Seminar Hall A',
    category: 'seminar',
    mode: 'hybrid',
    organizer: 'Energy Club',
    department: 'Electrical Engineering',
    googleFormLink: getFormLink(1),
    attendees: 80,
    maxCapacity: 100,
  },
  {
    id: '6',
    title: 'Photography Workshop: Capture the Moment',
    description: 'Learn professional photography techniques including composition, lighting, and post-processing.',
    date: getFutureDate(20),
    time: '11:00 AM',
    venue: 'Art Studio',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Photography Club',
    department: 'Fine Arts',
    googleFormLink: getFormLink(2),
    attendees: 25,
    maxCapacity: 30,
  },
  {
    id: '7',
    title: 'Startup Pitch Competition',
    description: 'Present your startup idea to a panel of investors and industry experts. Win funding and mentorship!',
    date: getFutureDate(25),
    time: '10:00 AM',
    venue: 'Business School Auditorium',
    category: 'tech',
    mode: 'offline',
    organizer: 'Entrepreneurship Cell',
    department: 'Business Administration',
    googleFormLink: getFormLink(0),
    attendees: 60,
    maxCapacity: 80,
  },
  {
    id: '8',
    title: 'Classical Music Night',
    description: 'An evening of Indian classical music featuring renowned artists and student performers.',
    date: getFutureDate(15),
    time: '6:30 PM',
    venue: 'Open Air Theatre',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Music Society',
    department: 'Student Affairs',
    googleFormLink: getFormLink(1),
    attendees: 120,
    maxCapacity: 200,
  },
  {
    id: '9',
    title: 'Web Development Bootcamp',
    description: 'Intensive 2-day bootcamp covering React, Node.js, and modern web development practices.',
    date: getFutureDate(0), // Today - Active event
    time: '9:00 AM',
    venue: 'Tech Lab 201',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Web Dev Club',
    department: 'Computer Science',
    googleFormLink: getFormLink(2),
    attendees: 35,
    maxCapacity: 40,
  },
  {
    id: '10',
    title: 'Career Fair 2025',
    description: 'Connect with top employers, explore internship opportunities, and get your resume reviewed.',
    date: getFutureDate(30),
    time: '10:00 AM',
    venue: 'Main Hall',
    category: 'seminar',
    mode: 'offline',
    organizer: 'Placement Cell',
    department: 'Career Services',
    googleFormLink: getFormLink(0),
    attendees: 250,
    maxCapacity: 500,
  },
  {
    id: '11',
    title: 'Yoga & Wellness Session',
    description: 'Start your morning with guided yoga and meditation for stress relief and mental clarity.',
    date: getFutureDate(2),
    time: '6:00 AM',
    venue: 'Sports Ground',
    category: 'sports',
    mode: 'offline',
    organizer: 'Wellness Club',
    department: 'Physical Education',
    googleFormLink: getFormLink(1),
    attendees: 40,
    maxCapacity: 50,
  },
  {
    id: '12',
    title: 'Data Science Symposium',
    description: 'Industry experts discuss the latest trends in data analytics, visualization, and business intelligence.',
    date: getFutureDate(22),
    time: '2:00 PM',
    venue: 'Conference Hall B',
    category: 'seminar',
    mode: 'hybrid',
    organizer: 'Data Science Club',
    department: 'Computer Science',
    googleFormLink: getFormLink(2),
    attendees: 90,
    maxCapacity: 120,
  },
  {
    id: '16',
    title: 'Cybersecurity Essentials Workshop',
    description: 'Learn about network security, ethical hacking basics, and protecting digital assets in this hands-on session.',
    date: getFutureDate(4),
    time: '2:00 PM',
    venue: 'IT Lab 102',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Cyber Club',
    department: 'Computer Science',
    googleFormLink: getFormLink(0),
    attendees: 28,
    maxCapacity: 40,
  },
  {
    id: '17',
    title: 'Annual Sports Day',
    description: 'A full day of athletic competitions including track events, field sports, and team games for all departments.',
    date: getFutureDate(10),
    time: '8:00 AM',
    venue: 'University Stadium',
    category: 'sports',
    mode: 'offline',
    organizer: 'Sports Council',
    department: 'Physical Education',
    googleFormLink: getFormLink(1),
    attendees: 350,
    maxCapacity: 500,
  },
  {
    id: '18',
    title: 'Blockchain Technology Seminar',
    description: 'Understanding decentralized systems, smart contracts, and the future of Web3 technologies.',
    date: getFutureDate(7),
    time: '11:00 AM',
    venue: 'Seminar Hall B',
    category: 'seminar',
    mode: 'hybrid',
    organizer: 'Tech Club',
    department: 'Computer Science',
    googleFormLink: getFormLink(2),
    attendees: 55,
    maxCapacity: 80,
  },
  {
    id: '19',
    title: 'Dance Workshop: Contemporary Fusion',
    description: 'Master contemporary dance techniques blending classical and modern styles with professional choreographers.',
    date: getFutureDate(6),
    time: '4:00 PM',
    venue: 'Dance Studio',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Dance Club',
    department: 'Fine Arts',
    googleFormLink: getFormLink(0),
    attendees: 18,
    maxCapacity: 25,
  },
  {
    id: '20',
    title: 'IoT Innovation Challenge',
    description: 'Build smart devices and IoT solutions using Arduino and Raspberry Pi. Best projects win exciting prizes!',
    date: getFutureDate(14),
    time: '9:00 AM',
    venue: 'Electronics Lab',
    category: 'hackathon',
    mode: 'offline',
    organizer: 'Electronics Club',
    department: 'Electrical Engineering',
    googleFormLink: getFormLink(1),
    attendees: 42,
    maxCapacity: 50,
  },
  {
    id: '21',
    title: 'Public Speaking Masterclass',
    description: 'Develop confidence, learn persuasion techniques, and master the art of impactful presentations.',
    date: getFutureDate(9),
    time: '3:00 PM',
    venue: 'Conference Room A',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Toastmasters Club',
    department: 'Communication',
    googleFormLink: getFormLink(2),
    attendees: 30,
    maxCapacity: 35,
  },
  {
    id: '22',
    title: 'Inter-Department Cricket Tournament',
    description: 'Annual cricket championship between departments. Register your team and compete for the trophy!',
    date: getFutureDate(16),
    time: '7:00 AM',
    venue: 'Cricket Ground',
    category: 'sports',
    mode: 'offline',
    organizer: 'Sports Council',
    department: 'Physical Education',
    googleFormLink: getFormLink(0),
    attendees: 160,
    maxCapacity: 200,
  },
  {
    id: '23',
    title: 'Film Making & Editing Workshop',
    description: 'Learn cinematography, video editing, and storytelling techniques from industry professionals.',
    date: getFutureDate(11),
    time: '10:00 AM',
    venue: 'Media Lab',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Film Club',
    department: 'Media Studies',
    googleFormLink: getFormLink(1),
    attendees: 22,
    maxCapacity: 30,
  },
  {
    id: '24',
    title: 'Mental Health Awareness Talk',
    description: 'Expert psychologists discuss stress management, work-life balance, and maintaining mental wellness.',
    date: getFutureDate(1),
    time: '2:30 PM',
    venue: 'Main Auditorium',
    category: 'seminar',
    mode: 'hybrid',
    organizer: 'Counseling Center',
    department: 'Student Affairs',
    googleFormLink: getFormLink(2),
    attendees: 180,
    maxCapacity: 300,
  },
  {
    id: '25',
    title: 'Robotics Competition 2025',
    description: 'Design, build, and program robots to complete challenging tasks. Open to all engineering students.',
    date: getFutureDate(21),
    time: '9:00 AM',
    venue: 'Robotics Lab',
    category: 'hackathon',
    mode: 'offline',
    organizer: 'Robotics Club',
    department: 'Mechanical Engineering',
    googleFormLink: getFormLink(0),
    attendees: 65,
    maxCapacity: 80,
  },
  {
    id: '26',
    title: 'Poetry Slam & Open Mic Night',
    description: 'Express yourself through poetry, spoken word, and creative performances in a supportive atmosphere.',
    date: getFutureDate(13),
    time: '6:00 PM',
    venue: 'Literary Cafe',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Literary Society',
    department: 'English',
    googleFormLink: getFormLink(1),
    attendees: 45,
    maxCapacity: 60,
  },
  {
    id: '27',
    title: 'Mobile App Development Sprint',
    description: 'Build a complete mobile app in 48 hours using Flutter or React Native with expert mentorship.',
    date: getFutureDate(19),
    time: '10:00 AM',
    venue: 'Innovation Hub',
    category: 'hackathon',
    mode: 'hybrid',
    organizer: 'App Dev Club',
    department: 'Computer Science',
    googleFormLink: getFormLink(2),
    attendees: 38,
    maxCapacity: 45,
  },
  // ==================== NEW UPCOMING EVENTS ====================
  {
    id: '28',
    title: 'Cloud Computing Fundamentals',
    description: 'Introduction to AWS, Azure, and Google Cloud. Learn to deploy scalable applications in the cloud.',
    date: getFutureDate(4),
    time: '10:00 AM',
    venue: 'IT Lab 201',
    category: 'workshop',
    mode: 'hybrid',
    organizer: 'Cloud Computing Club',
    department: 'Computer Science',
    googleFormLink: getFormLink(0),
    attendees: 32,
    maxCapacity: 50,
  },
  {
    id: '29',
    title: 'Annual Theatre Festival',
    description: 'A week-long celebration of drama featuring student productions, workshops, and guest performances.',
    date: getFutureDate(23),
    time: '4:00 PM',
    venue: 'Drama Theatre',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Theatre Society',
    department: 'Fine Arts',
    googleFormLink: getFormLink(1),
    attendees: 180,
    maxCapacity: 250,
  },
  {
    id: '30',
    title: 'Swimming Championship 2025',
    description: 'Inter-college swimming competition with events in freestyle, backstroke, butterfly, and relay.',
    date: getFutureDate(17),
    time: '8:00 AM',
    venue: 'Olympic Pool',
    category: 'sports',
    mode: 'offline',
    organizer: 'Aquatics Club',
    department: 'Physical Education',
    googleFormLink: getFormLink(2),
    attendees: 85,
    maxCapacity: 120,
  },
  {
    id: '31',
    title: 'Digital Marketing Bootcamp',
    description: 'Master SEO, social media marketing, content strategy, and analytics in this intensive workshop.',
    date: getFutureDate(6),
    time: '9:30 AM',
    venue: 'Business Lab',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Marketing Club',
    department: 'Business Administration',
    googleFormLink: getFormLink(0),
    attendees: 40,
    maxCapacity: 45,
  },
  {
    id: '32',
    title: 'Quantum Computing Symposium',
    description: 'Leading researchers discuss quantum algorithms, hardware developments, and industry applications.',
    date: getFutureDate(28),
    time: '10:00 AM',
    venue: 'Conference Hall A',
    category: 'seminar',
    mode: 'hybrid',
    organizer: 'Physics Society',
    department: 'Physics',
    googleFormLink: getFormLink(1),
    attendees: 75,
    maxCapacity: 100,
  },
  {
    id: '33',
    title: 'International Food Festival',
    description: 'Experience cuisines from around the world prepared by student clubs. Cultural performances included.',
    date: getFutureDate(15),
    time: '12:00 PM',
    venue: 'Central Lawn',
    category: 'cultural',
    mode: 'offline',
    organizer: 'International Students Association',
    department: 'Student Affairs',
    googleFormLink: getFormLink(2),
    attendees: 400,
    maxCapacity: 600,
  },
  {
    id: '34',
    title: 'Game Development Workshop',
    description: 'Create your first video game using Unity. Learn game design principles and C# programming basics.',
    date: getFutureDate(8),
    time: '2:00 PM',
    venue: 'Gaming Lab',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Game Dev Society',
    department: 'Computer Science',
    googleFormLink: getFormLink(0),
    attendees: 28,
    maxCapacity: 35,
  },
  {
    id: '35',
    title: 'Badminton Tournament',
    description: 'Singles and doubles categories open to all students. Registration includes practice sessions.',
    date: getFutureDate(12),
    time: '3:00 PM',
    venue: 'Indoor Sports Hall',
    category: 'sports',
    mode: 'offline',
    organizer: 'Badminton Club',
    department: 'Physical Education',
    googleFormLink: getFormLink(1),
    attendees: 64,
    maxCapacity: 80,
  },
  {
    id: '36',
    title: 'UI/UX Design Masterclass',
    description: 'Learn user research, wireframing, prototyping, and design systems using Figma and Adobe XD.',
    date: getFutureDate(5),
    time: '11:00 AM',
    venue: 'Design Studio',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Design Club',
    department: 'Fine Arts',
    googleFormLink: getFormLink(2),
    attendees: 25,
    maxCapacity: 30,
  },
  {
    id: '37',
    title: 'Astronomy Night: Stargazing Session',
    description: 'Observe planets, constellations, and deep-sky objects through powerful telescopes on campus.',
    date: getFutureDate(10),
    time: '8:00 PM',
    venue: 'Observatory Terrace',
    category: 'seminar',
    mode: 'offline',
    organizer: 'Astronomy Club',
    department: 'Physics',
    googleFormLink: getFormLink(0),
    attendees: 50,
    maxCapacity: 60,
  },
  {
    id: '38',
    title: 'Debate Championship 2025',
    description: 'Annual inter-college debate competition on current affairs and policy topics. Cash prizes await!',
    date: getFutureDate(20),
    time: '10:00 AM',
    venue: 'Seminar Hall C',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Debate Society',
    department: 'English',
    googleFormLink: getFormLink(1),
    attendees: 60,
    maxCapacity: 80,
  },
  {
    id: '39',
    title: 'Python for Data Analysis',
    description: 'Hands-on workshop covering pandas, numpy, matplotlib for data manipulation and visualization.',
    date: getFutureDate(3),
    time: '10:00 AM',
    venue: 'Computer Lab 102',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Data Science Club',
    department: 'Computer Science',
    googleFormLink: getFormLink(2),
    attendees: 42,
    maxCapacity: 50,
  },
  {
    id: '40',
    title: 'Chess Championship',
    description: 'Open chess tournament with classical and rapid formats. All skill levels welcome.',
    date: getFutureDate(14),
    time: '9:00 AM',
    venue: 'Recreation Room',
    category: 'sports',
    mode: 'offline',
    organizer: 'Chess Club',
    department: 'Student Affairs',
    googleFormLink: getFormLink(0),
    attendees: 48,
    maxCapacity: 64,
  },
  {
    id: '41',
    title: 'Entrepreneurship Summit 2025',
    description: 'Successful founders share their journeys. Includes networking sessions and startup showcases.',
    date: getFutureDate(26),
    time: '9:00 AM',
    venue: 'Business Auditorium',
    category: 'seminar',
    mode: 'hybrid',
    organizer: 'E-Cell',
    department: 'Business Administration',
    googleFormLink: getFormLink(1),
    attendees: 200,
    maxCapacity: 300,
  },
  {
    id: '42',
    title: 'Electronic Music Production',
    description: 'Learn beat making, mixing, and mastering using Ableton Live and FL Studio.',
    date: getFutureDate(9),
    time: '3:00 PM',
    venue: 'Music Studio',
    category: 'workshop',
    mode: 'offline',
    organizer: 'EDM Club',
    department: 'Fine Arts',
    googleFormLink: getFormLink(2),
    attendees: 15,
    maxCapacity: 20,
  },
  {
    id: '43',
    title: 'Hackathon: HealthTech Innovation',
    description: 'Build healthcare solutions using AI, IoT, and mobile tech. Mentorship from medical professionals.',
    date: getFutureDate(24),
    time: '8:00 AM',
    venue: 'Innovation Center',
    category: 'hackathon',
    mode: 'hybrid',
    organizer: 'Health Tech Club',
    department: 'Biotechnology',
    googleFormLink: getFormLink(0),
    attendees: 80,
    maxCapacity: 100,
  },
  {
    id: '44',
    title: 'Table Tennis League',
    description: 'Weekly league format with playoffs. Individual and doubles categories available.',
    date: getFutureDate(7),
    time: '5:00 PM',
    venue: 'TT Room',
    category: 'sports',
    mode: 'offline',
    organizer: 'TT Club',
    department: 'Physical Education',
    googleFormLink: getFormLink(1),
    attendees: 32,
    maxCapacity: 40,
  },
  {
    id: '45',
    title: 'Fashion Show: Threads 2025',
    description: 'Annual fashion showcase featuring student designers. Themes: sustainable fashion and cultural fusion.',
    date: getFutureDate(27),
    time: '7:00 PM',
    venue: 'Grand Ballroom',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Fashion Club',
    department: 'Fine Arts',
    googleFormLink: getFormLink(2),
    attendees: 350,
    maxCapacity: 500,
  },
  {
    id: '46',
    title: 'Linux System Administration',
    description: 'Master command line, shell scripting, and server management for enterprise environments.',
    date: getFutureDate(11),
    time: '10:00 AM',
    venue: 'Server Room Lab',
    category: 'workshop',
    mode: 'offline',
    organizer: 'Open Source Club',
    department: 'Computer Science',
    googleFormLink: getFormLink(0),
    attendees: 22,
    maxCapacity: 25,
  },
  {
    id: '47',
    title: 'Marathon: Run for Health',
    description: '5K, 10K, and half-marathon categories. All participants receive medals and refreshments.',
    date: getFutureDate(29),
    time: '6:00 AM',
    venue: 'Campus Circuit',
    category: 'sports',
    mode: 'offline',
    organizer: 'Athletics Club',
    department: 'Physical Education',
    googleFormLink: getFormLink(1),
    attendees: 280,
    maxCapacity: 400,
  },
  // ==================== COMPLETED EVENTS (Past dates) ====================
  {
    id: '13',
    title: 'Orientation Week 2024',
    description: 'Welcome session for new students with campus tours and introduction to university life.',
    date: getFutureDate(-30),
    time: '9:00 AM',
    venue: 'Main Auditorium',
    category: 'seminar',
    mode: 'offline',
    organizer: 'Student Council',
    department: 'Student Affairs',
    googleFormLink: getFormLink(0),
    attendees: 600,
    maxCapacity: 600,
  },
  {
    id: '14',
    title: 'Coding Competition 2024',
    description: 'Annual competitive programming event with algorithmic challenges for all skill levels.',
    date: getFutureDate(-15),
    time: '10:00 AM',
    venue: 'Computer Lab 101',
    category: 'tech',
    mode: 'offline',
    organizer: 'Coding Club',
    department: 'Computer Science',
    googleFormLink: getFormLink(1),
    attendees: 75,
    maxCapacity: 75,
  },
  {
    id: '15',
    title: 'Art Exhibition: Colors of Culture',
    description: 'Showcase of student artwork exploring themes of cultural diversity and heritage traditions.',
    date: getFutureDate(-7),
    time: '11:00 AM',
    venue: 'Art Gallery',
    category: 'cultural',
    mode: 'offline',
    organizer: 'Art Society',
    department: 'Fine Arts',
    googleFormLink: getFormLink(2),
    attendees: 200,
    maxCapacity: 200,
  },
];

export const categories: { value: EventCategory; label: string; color: string }[] = [
  { value: 'workshop', label: 'Workshop', color: 'category-workshop' },
  { value: 'cultural', label: 'Cultural', color: 'category-cultural' },
  { value: 'tech', label: 'Tech', color: 'category-tech' },
  { value: 'sports', label: 'Sports', color: 'category-sports' },
  { value: 'seminar', label: 'Seminar', color: 'category-seminar' },
  { value: 'hackathon', label: 'Hackathon', color: 'category-tech' },
];

export const getCategoryColor = (category: EventCategory): string => {
  const cat = categories.find(c => c.value === category);
  return cat?.color || 'category-tech';
};
